### ISSUE TITLE
Get password 

### ISSUE THREAD

**Issue by LKirst** [ewjoachim/bitwarden-keyring#9]
I can create a new item: 
```
$ keyring set hello world
Password for 'world' in 'hello':
Created.
```

The bitwarden-cli shows the new item as expected: `$ bw get item hello`

But `keyring get hello world` doesn't return anything. (It doesn't raise an error either.)

I'm on Win10 with bitwarden-cli  version 2023.5.0. Could you help me to troubleshoot the issue? I don't know where to start.

**Comment by ewjoachim** [comment]
Hey, I haven't been spending a lot of time on this project lately, so I may not be of tremedous help here but... Have you tried using a breakpoint to figure out what command the wrapper executes on bw, what the result is etc ?

I'd like to say I can try reproducing on my end but I'm not sure when I'll have the setup for doing so.

**Comment by ewjoachim** [comment]
Ok, I analyzed what's happening:
When you set a secret with keyring, you provide a "service" ("hello" in your case). This service is saved both as the secret name in bw, and as a URI of the secret.
When you get a secret, under the hood, bitwarden-keyring uses bw's own mechanism for retrieving the secret linked to the same `URI`, using the service as the "URL we're trying to match", using `bw list items --url <service>`. The problem is that when the service you provide doesn't look enough like a URI, bitwarden doesn't match it. 

That seems to be a limitation with [Bitwarden](https://github.com/bitwarden/clients/issues/4831#issuecomment-1443941510): it only recognizes a match when there's a TLD in the URI hostname. And bitwarden keyring considers that the `service` that keyring provides is the said URI.

The same example you provided works if instead of `hello` you use `hello.com`.

All clear ?

**Comment by LKirst** [comment]
Thank you so much for your answer!
